### ISSUE TITLE
Put request throws error with headers option

### ISSUE THREAD

**Issue by keller35** [request/request-promise#128]
I got an error from a PUT request.But i find it can work without the header option.
The request with a header options is like this:
```
'use strict';
var rp = require("request-promise");

return rp({
  method: 'PUT',
  uri: 'http://v2.openapi.ele.me/restaurant/62028381/order_mode/?consumer_key=0170804777&sig=bc8b56be4f9d33942eb22bd66ab1f2a49eea91f4&timestamp=1465890208',
  body: {
    order_mode: 1
  },
  json: true,
  headers: {
    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8"
  },
}).then(body => {
  console.log(body);
});
```
And the error is:
```
/node_modules/request/lib/querystring.js:44
  return str.replace(/[!'()*]/g, function (c) {
             ^

TypeError: str.replace is not a function
    at Querystring.rfc3986 (/Users/keller/xfxb/brownie/node_modules/request/lib/querystring.js:44:14)
    at Request.json (/Users/keller/xfxb/brownie/node_modules/request/request.js:1201:30)
    at Request.init (/Users/keller/xfxb/brownie/node_modules/request/request.js:421:10)
    at Request.RP$initInterceptor [as init] (/Users/keller/xfxb/brownie/node_modules/request-promise/lib/rp.js:123:25)
    at new Request (/Users/keller/xfxb/brownie/node_modules/request/request.js:142:8)
```
Is this a problem from the module?

**Comment by analog-nico** [comment]
Interesting finding!

However, this is related to Request. Request-Promise is only extending Request in regard to promise handling.

Please open an issue for the [Request project](https://github.com/request/request/issues). You may use the following example code. (I took your code and converted it to using a callback instead of promises.)

``` js
'use strict';
var request = require("request");

request({
  method: 'PUT',
  uri: 'http://v2.openapi.ele.me/restaurant/62028381/order_mode/?consumer_key=0170804777&sig=bc8b56be4f9d33942eb22bd66ab1f2a49eea91f4&timestamp=1465890208',
  body: {
    order_mode: 1
  },
  json: true,
  headers: {
    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8"
  },
}, (err, response, body) => {
  console.log(body);
});
```

**Comment by keller35** [comment]
Thanks a lot.
I have opened an [issue](https://github.com/request/request/issues/2245) for the Request project.And i will close this issue.^_^

**Comment by Sudhakar12297** [comment]
Just remove
 headers: {
    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8"
  }
from the code!!
It will work.
