### ISSUE TITLE
Using proxy

### ISSUE THREAD

**Issue by omidn** [request/request-promise#130]
I'm wondering if it is possible to use proxy with request-promise too as for original request module.

here is explained how to set a proxy to tor in request, but providing the same options for request-promise seem not to be working..

Link to request's proxy example:
https://github.com/request/request/tree/master/examples#proxys

**Comment by analog-nico** [comment]
Hi @omidn I see no reason why it shouldn't. Technically, Request-Promise is just calling Request with passing a callback.

Please compare your two implementations if they are identical and if they use the same Request version. If you can't spot anything what is the error you get in the Request-Promise version?

**Comment by analog-nico** [comment]
Did you find something out worth sharing @omidn ?

**Comment by omidn** [comment]
@analog-nico I'm afraid not yet. I'll try to dig more and find it out.

**Comment by Ennelya** [comment]
I use request-promise@3.0.0 and passing proxy key-value to the options object of the request works for me, i.e:
request.post({
            proxy: 'localhost:port',
            url: "yourUrl",
           ...etc
   } )

**Comment by RomanBON** [comment]
Hello, people! Someone solved this problem?

**Comment by bannerchi** [comment]
@RomanBON  try like this :
```javascript
var proxyUrl = "http://" + user + ":" + password + "@" + host + ":" + port;

var proxiedRequest = request.defaults({'proxy': proxyUrl});
proxiedRequest.get('http://foo.bar')

```

[requst issues here](https://github.com/request/request/issues/894)

**Comment by k0pernikus** [comment]
@bannerchi Thank you for pointing this out and I can confirm your approach is working

I had a very hard time configuring the proxy using request/request-promise library as I expected to be able to set it via the requestOptions like:

        const options: rp.OptionsWithUri = {
            "uri": "http://some-website.com",
            "method": "GET",
            "proxy": "http://my-proxy.com:3819",
        };
        const result = await rp(options);

which produced connection refused errors.

**Comment by heshaShawky** [comment]
I'm getting 500 internal error with all above solutions! on postman and the console return error 
```bash
Error: tunneling socket could not be established, cause=read ECONNRESET +17663ms
RequestError: Error: tunneling socket could not be established, cause=read ECONNRESET
    at new RequestError (/Volumes/Partion-2/Projects/cars-blog/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Volumes/Partion-2/Projects/cars-blog/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Volumes/Partion-2/Projects/cars-blog/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Volumes/Partion-2/Projects/cars-blog/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.onRequestError (/Volumes/Partion-2/Projects/cars-blog/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:189:13)
    at ClientRequest.onError (/Volumes/Partion-2/Projects/cars-blog/node_modules/tunnel-agent/index.js:179:21)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:189:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
