### ISSUE TITLE
[RequestError: Error: Argument error, options.body.]

### ISSUE THREAD

**Issue by imjeffparedes** [request/request-promise#204]
This is the same code that I was using hence working but on this one it says Argument error,

My code is

```
createSession(user, callback){
		    // Configure the request
		    var options = {
		        method: 'POST',
		        uri: config.api.reddeph+'getsession/',
		        body: {
	              	username: user.username,
	              	password : crypto.createHash('md5').update(user.password).digest("hex")
            	},
			    timeout: 60000,
			    resolveWithFullResponse : true
		    }
		    // Start the request

		    rp(options)
		    	.then(function (response){
					log.notice(Object.assign(response,{event:'ReddePh API Response'}));
		    		callback(null, response.body)
		    	})
		    	.catch(function (err) {
		        // Handle failed request...
					callback(err || new Error('ReddePh API Failed'),null)
					log.notice(Object.assign(err,{event:'ReddePh API Error'}));
				});
	}
```

Error
```
An Error Occured { [RequestError: Error: Argument error, options.body.]
4|iamax    |   name: 'RequestError',
4|iamax    |   message: 'Error: Argument error, options.body.',
4|iamax    |   cause: [Error: Argument error, options.body.],
4|iamax    |   error: [Error: Argument error, options.body.],
4|iamax    |   options: 
4|iamax    |    { method: 'POST',
4|iamax    |      uri: 'https://uat.api.reddeph.com/index.php/api/loadservices/getsession/',
4|iamax    |      body: 
4|iamax    |       { username: 'CTI_API',
4|iamax    |         password: '373cca7fd0433851d0752434259a6208' },
4|iamax    |      timeout: 60000,
4|iamax    |      resolveWithFullResponse: true,
4|iamax    |      callback: [Function: RP$callback],
4|iamax    |      transform: undefined,
4|iamax    |      simple: true,
4|iamax    |      transform2xxOnly: false },
4|iamax    |   response: undefined }
4|iamax    | TypeError: first argument must be a string or Buffer
4|iamax    |     at ClientRequest.OutgoingMessage.write (_http_outgoing.js:447:11)
4|iamax    |     at Request.write (/Users/pmgcti/Documents/cti/project/dev/loadwallet/airtimeload-iamax-gateway/node_modules/request-promise/node_modules/request/request.js:1514:27)
4|iamax    |     at end (/Users/pmgcti/Documents/cti/project/dev/loadwallet/airtimeload-iamax-gateway/node_modules/request-promise/node_modules/request/request.js:552:18)
4|iamax    |     at Immediate._onImmediate (/Users/pmgcti/Documents/cti/project/dev/loadwallet/airtimeload-iamax-gateway/node_modules/request-promise/node_modules/request/request.js:581:7)
4|iamax    |     at processImmediate [as _immediateCallback] (timers.js:383:17)
4|iamax    | Uncaught Error { [TypeError: first argument must be a string or Buffer]
4|iamax    |   stackframes: 
4|iamax    |    [ { file_name: '_http_outgoing.js', line_number: 447 },
4|iamax    |      { file_name: '/Users/pmgcti/Documents/cti/project/dev/loadwallet/airtimeload-iamax-gateway/node_modules/request-promise/node_modules/request/request.js',
4|iamax    |        line_number: 1514 },
4|iamax    |      { file_name: '/Users/pmgcti/Documents/cti/project/dev/loadwallet/airtimeload-iamax-gateway/node_modules/request-promise/node_modules/request/request.js',
4|iamax    |        line_number: 552 },
4|iamax    |      { file_name: '/Users/pmgcti/Documents/cti/project/dev/loadwallet/airtimeload-iamax-gateway/node_modules/request-promise/node_modules/request/request.js',
4|iamax    |        line_number: 581 },
4|iamax    |      { file_name: 'timers.js', line_number: 383 } ] }

````

**Comment by imjeffparedes** [comment]
ok I used body: {body:JSON.stringify({data})},  seems to work.

**Comment by angelbeltran** [comment]
I think you mean to add the 'json: true' option! :)

**Comment by Sajeenthiran** [comment]
add json : true

  request({
    url : url,
    method :"POST",
    headers : {
        "content-type": "application/json",
    },
    body: body,
    json: true
},
