### ISSUE TITLE
Error: Cannot find module '../'

### ISSUE THREAD

**Issue by relgames** [request/request-promise#229]
package.json:

    {
      "name": "api-gateway",
      "version": "0.1.0",
      "dependencies": {
        "request": "^2.83.0",
        "request-promise-native": "^1.0.5",
        "server": "1.0.0-beta.2"
      },
      "scripts": {
        "start": "node index.js",
        "test": "jest --coverage --forceExit"
      }
    }

index.js:

    'use strict';

    const server = require('server');
    const {get, post, put, del} = server.router;

    const request = require('request-promise-native');

    const myUrl = 'https://google.com';

    server(get('/story/:id', async ctx => {
        const api = await request(`${myUrl}/test`);
        console.log(api);
        ctx.res.send('test');
    }));

Fails with:

    module.js:487
        throw err;
        ^
    
    Error: Cannot find module '../'
        at Function.Module._resolveFilename (module.js:485:15)
        at Function.Module._load (module.js:437:25)
        at Module.require (module.js:513:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/Users/oleg/work/test/api-gateway/node_modules/request-promise-native/node_modules/request-promise-core/configure/request2.js:3:12)
        at Module._compile (module.js:569:30)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:503:32)
        at tryModuleLoad (module.js:466:12)
        at Function.Module._load (module.js:458:3)
    
    Process finished with exit code 1

**Comment by relgames** [comment]
Please disregard, I had node_modules broken.
