### ISSUE TITLE
I get RequestError: Error: read ECONNRESET

### ISSUE THREAD

**Issue by fakirpic** [request/request-promise#235]
this is my code when i run under windows and proxy over fiddler web debugger. it works nice without any problem.

```
var minmins = 150;
var url = require('url');
var Promise = require("bluebird");
const domainim= 'example.com';
let request = require('requestretry').defaults({
		jar : true,
		timeout : 120000
	});
request=Promise.promisifyAll(request);
req = require('request');
var fs = require('fs');
var rp = require('request-promise').defaults({ simple: false });

var linkler = [];
var timeoutsure = 120 * 1000;
const hiz=20;
var separateReqPool = {
	maxSockets : hiz
};

let success = 0, fail = 0, toplam = 0, hilomins = 0;
let adet = 0;
let jardata = {};
let baslama = Math.round(new Date().getTime() / 1000);

function texts(l) {
	var t = "";
	var p = "abcdefghijklmnopqrstuvwxyz0123456789";
	for (var i = 0; i < l; i++) {
		t += p.charAt(Math.floor(Math.random() * p.length));
	}
	return t;
}


fs.readFile("data.txt", function (err, data) {
	if (err)
		throw err;
	data = data.toString().replace("\r", "");
	data = data.split(/\r\n|\r|\n/g);
	console.log("toplam data : " + data.length);
	toplam = data.length;

return Promise.map(data, function (line) {
	jardata[line.split(" ")[0]] = rp.jar();
	return rp({
		url : 'http://'+domainim+'/',
		jar : jardata[line.split(" ")[0]],
		headers : {
			'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36'
		},
		maxAttempts : 15,
		retryDelay : 2000,
		followRedirect : true,
		proxy :"http://127.0.0.1:8888",
		timeout : timeoutsure,
		pool : separateReqPool
	}).then(function (response) {
			adet++;
			data = {
				username : line.split(" ")[0],
				password : line.split(" ")[1],
				submit : "Login"
			};
			rp({
				method: 'POST',
				url : 'http://'+domainim+'/dologin/',
				jar : jardata[line.split(" ")[0]],
				headers : {
					'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36'
				},
				maxAttempts : 15,
				retryDelay : 2000,
				followRedirect : false,
				followAllRedirects : false,
				proxy :"http://127.0.0.1:8888",
				timeout : timeoutsure,
				pool : separateReqPool,
				form : data
			}).then(function (body) {
				adet++;
					rp({
						url : 'http://'+domainim+'/',
						jar : jardata[line.split(" ")[0]],
						headers : {
							'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36'
						},
						maxAttempts : 15,
						retryDelay : 2000,
						followRedirect : true,
						proxy :"http://127.0.0.1:8888",
						timeout : timeoutsure,
						pool : separateReqPool
					}).then(function (body) {
						adet++;
							if(body.indexOf('id="cb_check2')>-1) {
								saglamhesap(line.split(" ")[0],line.split(" ")[1],body.split('id="cb_check2">')[1].split('<')[0]);
								success++;
								if (parseFloat(body.split('id="cb_check2">')[1].split('<')[0]) >= minmins) {
									hilomins++;
									minsyaz(line.split(" ")[0],line.split(" ")[1],body.split('id="cb_check2">')[1].split('<')[0]);
								} else {

									rp({
										url : 'http://'+domainim+'/refreshcheck/',
										jar : jardata[line.split(" ")[0]],
										headers : {
											'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36'
										},
										maxAttempts : 15,
										retryDelay : 2000,
										followRedirect : true,
										proxy :"http://127.0.0.1:8888",
										timeout : timeoutsure,
										pool : separateReqPool
									}).then(function (body) {
										adet++;
										if (parseFloat(body)>= minmins){
										hilomins++;
										minsyaz(line.split(" ")[0], line.split(" ")[1], parseFloat(body));
										}
										
									});
								}
							} else {
								fail++;
							}
						
					});

			});
	});
}, { concurrency: 50});


						
});

function onExit() {
	console.log('\n%d sec,\n%d total,\n%d true,\n%d shit,\n%d big mins,\n---------------------\n',
		(Math.round(new Date().getTime() / 1000)) - baslama, toplam, success, fail, hilomins);
}
process.on('exit', onExit);

function saglamhesap(id, pass, mins) {
	console.log(id + " " + pass + " " + mins);
	var fd = fs.openSync("trueguys.txt", 'a+');
	fs.writeSync(fd, id + " " + pass + " " + mins + "\r\n");
	fs.closeSync(fd);

}

function minsyaz(id, pass, mins) {
	console.log(id + " " + pass + " " + mins);
	var fd = fs.openSync("trueman.txt", 'a+');
	fs.writeSync(fd, id + " " + pass + " " + mins + "\r\n");
	fs.closeSync(fd);

}


```

but when i comment proxy lines, dont proxy the connection i get these errors and and process exits only in a few seconds, instead of thousands . 
what is the thing magic doing fiddler and my nodejs script cant?

Unhandled rejection RequestError: Error: read ECONNRESET
    at new RequestError (C:\Users\Administrator\Desktop\data\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\Administrator\Desktop\data\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\Administrator\Desktop\data\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\Administrator\Desktop\data\node_modules\request\request.js:188:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (C:\Users\Administrator\Desktop\imajbet\node_modules\request\request.js:884:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by analog-nico** [comment]
Please start by adding proper error handling by adding `.catch(...)` blocks like you can see in all examples of the [cheat sheet](https://github.com/request/request-promise#cheat-sheet). That will allow you to identify the individual call that is returning the ECONNRESET error.

In addition, please read my response in [this issue](https://github.com/request/request-promise/issues/147) as it addresses the very same error.

**Comment by fakirpic** [comment]
i will add catch and put the logs here again.

**Comment by fakirpic** [comment]
it gives me this on catch(err) , just more detailed unhelpful logs :(

```
{ RequestError: Error: read ECONNRESET
    at new RequestError (C:\Users\Administrator\Desktop\data\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\Administrator\Desktop\data\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\Administrator\Desktop\data\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\Administrator\Desktop\data\node_modules\request\request.js:188:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (C:\Users\Administrator\Desktop\data\node_modules\request\request.js:884:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'RequestError',
  message: 'Error: read ECONNRESET',
  cause: { Error: read ECONNRESET
    at _errnoException (util.js:1031:13)
    at TCP.onread (net.js:619:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' },
  error: { Error: read ECONNRESET
    at _errnoException (util.js:1031:13)
    at TCP.onread (net.js:619:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' },
  options:
   { simple: false,
     url: 'http://example.com/',
     jar: RequestJar { _jar: [CookieJar] },
     headers:
      { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36' },
     maxAttempts: 15,
     retryDelay: 2000,
     followRedirect: true,
     timeout: 120000,
     pool: { maxSockets: 20, 'http:': [Agent] },
     callback: [Function: RP$callback],
     transform: undefined,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: undefined }
```

**Comment by analog-nico** [comment]
In addition, please read my response in [this issue](https://github.com/request/request-promise/issues/147) as it addresses the very same error.

**Comment by fakirpic** [comment]
but code works when i change }, { concurrency: 50}); to }, { concurrency: 1});, on promise. but much slower.
i think it is about using re-using same sockets for http connections as possible. i will try to make search if possible to use this on nodejs

**Comment by analog-nico** [comment]
Exactly, it may be about low level socket management if the cause originates on your side. However, it could also be your server who can’t handle that many parallel connections. To further distinguish if the cause is originating on your or the server’s side you should ideally monitor and analyze the TCP/IP traffic using WireShark for example. If the cause really is on your side then I hope the information in [the issue](https://github.com/request/request-promise/issues/147) I already linked above helps you to find the parts that you need to configure in respect to node.js’ core libraries.

**Comment by cybairfly** [comment]
This issue was in my case caused by this missing request option: `gzip: true`
