### ISSUE TITLE
400 Malformed error on rp client

### ISSUE THREAD

**Issue by ridhwaans** [request/request-promise#264]
I have to preface this by saying the http 400 error only started consistently occurring yesterday. Client-side always used to be getting I 200 prior. I cant identify the root cause. 
 
**Endpoint(s):**
[spotify api](https://beta.developer.spotify.com/console/get-album/) GET /v1/albums/{album_id}
**Scope(s):**
Api and request-promise client are using temporary OAuth Token
**Steps to reproduce:**  
Basically this is the `options` request I use in the request-promise client  
```
options = 
{
  "body": {
    "external_id": "1ekH0EKwh4eNXqdi9Fvelt"
  },
  "headers": {
    "Accept": "application/json",
    "Authorization": "Bearer BQCkyEdWB37BAgUFtvpM_iB8ST7btws46lsH7y16TUf1RF6zHSUFbQcHAhHpFLJrzpnbeK1BJK_OVobcNCu5ke1sgrgkjeWX51CVaeQoMP1e09rm_mM0cPNHq3XRWIbNPCT6gpuOlpvjqRhPGf28-74p-NqAoOs",
    "Content-Type": "application/json"
  },
  "json": true,
  "method": "GET",
  "resolveWithFullResponse": true,
  "timeout": 10000,
  "uri": "https://api.spotify.com/v1/albums/1ekH0EKwh4eNXqdi9Fvelt"
}
```
code snippet from request-promise client  
 ```
return rp(options)
       .then(this._parseResponse)
       .delay(delay)
       .then((response)=> {
          return new Promise( (resolve) => {
            if (callback) { return callback(null, response); }
            return resolve(response);
          });
        })
        .catch(rp_errors.StatusCodeError,((error) => {
            throw new errors.ResponseError(request, error.statusCode, error.message);
          }
        ))
        .catch(rp_errors.RequestError,((error) => {
            if(error.cause.code === 'ETIMEDOUT' || error.cause.code === 'ESOCKETTIMEDOUT')
              throw new errors.TimeoutError(request, error);
            throw error;
          }
        ))
        .catch((error) => {
          if (callback) {return callback(error)};
          throw error;
        });
```
FYI I tried sending the request with no cache, using an older git version, and on another computer, still getting 400 consistently (used to return 200 and the request hasnt changed).   

See https://github.com/ridhwaans/homehost/blob/master/lib/api-client.js (uses request-promise) and
https://github.com/ridhwaans/homehost/blob/master/server.js for full details  

**Steps to reproduce expected result**  

- Open the API Console
- Go to the https://beta.developer.spotify.com/console/get-album page
- Generate auth token and select Fill sample data or use album id 4G3ZBFg8MpTSDxDQ3m2BCb
- response should be http 200 and return valid json
- Expected behaviour:
- Http 200 response should return json like this  

```
{
  "album_type": "album",
  ...
  "href": "https://api.spotify.com/v1/albums/4G3ZBFg8MpTSDxDQ3m2BCb",
  "id": "4G3ZBFg8MpTSDxDQ3m2BCb",
  "images": [...]
  ...
}
```
**Actual behaviour:**
400 Bad Request (consistently)

**Full stack trace**

```
Generating data for Music...
[0] GET: /mnt/c/Users/ridhwaan/Music/homehost/_music/#Twerkit 1ekH0EKwh4eNXqdi9Fvelt
[0] url: https://api.spotify.com/v1/albums/1ekH0EKwh4eNXqdi9Fvelt
[0] {"method":"GET","uri":"https://api.spotify.com/v1/albums/1ekH0EKwh4eNXqdi9Fvelt","headers":{"Authorization":"Bearer BQBRyWhUyKqHmrXIfLUL6xTilbySK-qaa7vAa8aD9m7G8Wc2Ljtqs7IxQjMJjP9rlp4sTOao26aX_w6OfAnVolJxxk4shC1N2cJVIMBBSwwbnPFYx6wpqZaNuUKJKZBWtzU8HBjM7HaXOHlS9HEwnBO3LHdUddU"},"timeout":10000,"resolveWithFullResponse":true,"json":true,"body":{"external_id":"1ekH0EKwh4eNXqdi9Fvelt"}}
[0] Music metadata could not be generated due to some error { ResponseError: 400 - "<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n  <title>Error 400 (Bad Request)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen
and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>400.</b> <ins>That’s an error.</ins>\n  <p>Your client has issued a malformed or illegal request.  <ins>That’s all we know.</ins>\n"
[0]     at rp.then.delay.then.catch (/mnt/c/Users/ridhwaan/Downloads/homehost-client-v1.1.0/lib/api-client.js:56:19)
[0]     at tryCatcher (/mnt/c/Users/ridhwaan/Downloads/homehost-client-v1.1.0/node_modules/bluebird/js/release/util.js:16:23)
[0]     at /mnt/c/Users/ridhwaan/Downloads/homehost-client-v1.1.0/node_modules/bluebird/js/release/catch_filter.js:17:41
[0]     at tryCatcher (/mnt/c/Users/ridhwaan/Downloads/homehost-client-v1.1.0/node_modules/bluebird/js/release/util.js:16:23)
[0]     at Promise._settlePromiseFromHandler (/mnt/c/Users/ridhwaan/Downloads/homehost-client-v1.1.0/node_modules/bluebird/js/release/promise.js:512:31)
[0]     at Promise._settlePromise (/mnt/c/Users/ridhwaan/Downloads/homehost-client-v1.1.0/node_modules/bluebird/js/release/promise.js:569:18)
[0]     at Promise._settlePromise0 (/mnt/c/Users/ridhwaan/Downloads/homehost-client-v1.1.0/node_modules/bluebird/js/release/promise.js:614:10)
[0]     at Promise._settlePromises (/mnt/c/Users/ridhwaan/Downloads/homehost-client-v1.1.0/node_modules/bluebird/js/release/promise.js:689:18)
[0]     at Async._drainQueue (/mnt/c/Users/ridhwaan/Downloads/homehost-client-v1.1.0/node_modules/bluebird/js/release/async.js:133:16)
[0]     at Async._drainQueues (/mnt/c/Users/ridhwaan/Downloads/homehost-client-v1.1.0/node_modules/bluebird/js/release/async.js:143:10)
[0]     at Immediate.Async.drainQueues [as _onImmediate] (/mnt/c/Users/ridhwaan/Downloads/homehost-client-v1.1.0/node_modules/bluebird/js/release/async.js:17:14)
[0]     at runCallback (timers.js:756:18)
[0]     at tryOnImmediate (timers.js:717:5)
[0]     at processImmediate [as _immediateCallback] (timers.js:697:5)
[0]   name: 'ResponseError',
[0]   request:
[0]    Album {
[0]      method: 'GET',
[0]      path: '/albums/1ekH0EKwh4eNXqdi9Fvelt',
[0]      timeout: 10000,
[0]      ensureHttps: false,
[0]      external_id: '1ekH0EKwh4eNXqdi9Fvelt' },
[0]   statusCode: 400 }
```

**Comment by ridhwaans** [comment]
fixed by removing the `body` field from `options`
