### ISSUE TITLE
Is it possible to POST form data and body data simultaneously? 

### ISSUE THREAD

**Issue by najiiali** [request/request-promise#271]
Hello,

I am trying to use this package to interact with the app publishing API for Apperian. I have been able to use it to send an .ipa file to Apperian, but when I try to send body data along with the .ipa, I get the following error:

```
{ RequestError: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at new RequestError (/Users/najeeali/Dropbox/Documents/Coda/JS/Node JS/request_promise/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/najeeali/Dropbox/Documents/Coda/JS/Node JS/request_promise/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/najeeali/Dropbox/Documents/Coda/JS/Node JS/request_promise/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/najeeali/Dropbox/Documents/Coda/JS/Node JS/request_promise/node_modules/request/request.js:185:22)
    at Request.emit (events.js:187:15)
    at Request.onRequestError (/Users/najeeali/Dropbox/Documents/Coda/JS/Node JS/request_promise/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:182:13)
    at writeAfterEndNT (_http_outgoing.js:639:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'RequestError',
  message: 'Error [ERR_STREAM_WRITE_AFTER_END]: write after end',
  cause:
   Error [ERR_STREAM_WRITE_AFTER_END]: write after end
       at write_ (_http_outgoing.js:580:17)
       at ClientRequest.write (_http_outgoing.js:575:10)
       at Request.write (/Users/najeeali/Dropbox/Documents/Coda/JS/Node JS/request_promise/node_modules/request/request.js:1495:27)
       at FormData.ondata (internal/streams/legacy.js:15:31)
       at FormData.emit (events.js:182:13)
       at FormData.CombinedStream.write (/Users/najeeali/Dropbox/Documents/Coda/JS/Node JS/request_promise/node_modules/combined-stream/lib/combined_stream.js:119:8)
       at DelayedStream.ondata (internal/streams/legacy.js:15:31)
       at DelayedStream.emit (events.js:182:13)
       at DelayedStream._handleEmit (/Users/najeeali/Dropbox/Documents/Coda/JS/Node JS/request_promise/node_modules/delayed-stream/lib/delayed_stream.js:82:15)
       at ReadStream.source.emit (/Users/najeeali/Dropbox/Documents/Coda/JS/Node JS/request_promise/node_modules/delayed-stream/lib/delayed_stream.js:29:19),
  error:
   Error [ERR_STREAM_WRITE_AFTER_END]: write after end
       at write_ (_http_outgoing.js:580:17)
       at ClientRequest.write (_http_outgoing.js:575:10)
       at Request.write (/Users/najeeali/Dropbox/Documents/Coda/JS/Node JS/request_promise/node_modules/request/request.js:1495:27)
       at FormData.ondata (internal/streams/legacy.js:15:31)
       at FormData.emit (events.js:182:13)
       at FormData.CombinedStream.write (/Users/najeeali/Dropbox/Documents/Coda/JS/Node JS/request_promise/node_modules/combined-stream/lib/combined_stream.js:119:8)
       at DelayedStream.ondata (internal/streams/legacy.js:15:31)
       at DelayedStream.emit (events.js:182:13)
       at DelayedStream._handleEmit (/Users/najeeali/Dropbox/Documents/Coda/JS/Node JS/request_promise/node_modules/delayed-stream/lib/delayed_stream.js:82:15)
       at ReadStream.source.emit (/Users/najeeali/Dropbox/Documents/Coda/JS/Node JS/request_promise/node_modules/delayed-stream/lib/delayed_stream.js:29:19),
   options:
   { method: 'POST',
     headers:
      { 'Content-Length': 94,
        'Content-Type': 'application/json',
        'X-TOKEN': '<MY TOKEN>' },
     url:
      'https://na01ws.apperian.com/v1/applications/<APP ID>',
     body:
      '{"version_num":"1","version_note":"Test","short_description":"Test","long_description":"Test"}',
     json: true,
     formData: { app_file: [ReadStream] },
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: undefined }
```

Does `write after end` mean Request-Promise is trying to send the file after the request has already been sent? Is it not possible to send both "body data" and "form data" together? Apperian _seemingly_ allows this sort of functionality with a cURL command:

```
curl -X POST https://na01ws.apperian.com/v1/applications/DzCbyyTyl_cner0hvbmRSA
     --header "Content-Type: application/json" --header "X-TOKEN: eTg8ktZXRqKIBJTHunwP6A"
     -F 'app_file=@MyApp.ipa'
     -F 'data={
           "version_num": "1.3",
           "version_note": "The completely patched first installment!"
        }'
```

To try and recreate what is happening above, using Node and Request-Promise, I am doing the following:

```
const requestPromiseNative = require("request-promise-native"),
      fs = require("fs");

// Create ReadStream to read file

  const fStream = fs.createReadStream("./files/file.ipa");

// Create JSON body data for submitting to Apperian

  const metadata = {
      version_num: "1",
      version_note: "Test",
      short_description: "Test",
      long_description: "Test"
  };

// Make POST request

  let options = {
    method: 'POST',
    headers: {
      "Content-Type": "application/json",
	"X-TOKEN": "<MY TOKEN>"
    },
    url: "https://na01ws.apperian.com/v1/applications/<APP ID>",
    body: metadata,
    json: true,
    formData: {
      "app_file": fStream,
    }
  };

  requestPromiseNative(options)
    .then(data => {
      console.log(data);
    }).catch(err => {
      console.log(err);
    });
```

I would appreciate any assistance on this issue. Thank you for making such an otherwise useful package!

**Comment by hiteshjoshi1** [comment]
I have the exact same problem... what was solution/ root cause?

**Comment by janober** [comment]
I had the same problem. For me the solution was to remove the "body" parameter completely and add also the other data to FormData.

**Comment by paxcom-sgarg** [comment]
but this is not the solution , i may need the body as well
