### ISSUE TITLE
The "request" library is not installed automatically anymore.

### ISSUE THREAD

**Issue by iwko** [request/request-promise#291]
I've got app(node 0.8.28) where i use `request-promise` in my package.json i've got dependencies:
`"request": "2.79.0",
"request-promise": "4.1.1",`. 
But i am getting error:
```
### The "request" library is not installed automatically anymore.
### But required by "request-promise".
###
### npm install request --save
###

	at  (/home/workspace/node_modules/request-promise/lib/rp.js:21)
	at Module._compile (module.js:449)
	at Module._extensions..js (module.js:467)
	at Module.load (module.js:356)
	at Module._load (module.js:312)
	at Module.require (module.js:362)
	at require (module.js:378)
	at  (/home/workspace/lib/helpers/pollution.js:1)
	at Module._compile (module.js:449)
	at Module._extensions..js (module.js:467)
	at Module.load (module.js:356)
[D 14:31:44.102Z Application.js:152] ---- Error: Problem running server class. ----
[D 14:31:44.102Z Application.js:153] non_object_property_load
[D 14:31:44.103Z Application.js:154] Cannot read property 'prototype' of undefined
[D 14:31:44.104Z Application.js:155] TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:538:43)
    at Object.<anonymous> (/home/workspace/node_modules/request/node_modules/http-signature/node_modules/sshpk/lib/ed-compat.js:25:6)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/workspace/node_modules/request/node_modules/http-signature/node_modules/sshpk/lib/private-key.js:17:16)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/workspace/node_modules/request/node_modules/http-signature/node_modules/sshpk/lib/utils.js:25:18)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
```
This app worked before without problems and nothing was changed on app side.  Both `request` and `request-promise` exists in `node_modules` directory

**Comment by pradiptabasu** [comment]
Hello,

I am facing the same issue.
Can you share your solution or how your are bypassing it ?

**Comment by analog-nico** [comment]
Hey @pradiptabasu , you need to install `request` yourself before you install `request-promise`. See the [installation instructions](https://github.com/request/request-promise#installation).

**Comment by MatthewDtotheG** [comment]
Hi @analog-nico, I am having this same issue and installing request before request-promise did not solve the problem. Any other ideas?

**Comment by analog-nico** [comment]
@MatthewDtotheG Do you have both libraries added to your `package.json`? What do `npm ls request` and `npm ls request-promise` output?

**Comment by MatthewDtotheG** [comment]
@analog-nico I figured out my issue. The `request library is not installed automatically anymore` error was being returned first but I found that it was actually being caused by a node modules error. `Module not found: Error: Can't resolve 'fs' in path/request`. After setting `fs` to empty in my webpack config both issues were resolved. `node: {fs: 'empty', net: 'empty'}`. Thanks for responding so quickly!

**Comment by slpixe** [comment]
In case anyone else runs into this issue recently via google search, I was encountering it with `node@10.16.0`, and its working on `node@10.16.1` likely due to a fix labled "fix esm load bug" in the node changelog

**Comment by ahmadasmndr** [comment]
> 
> 
> Hey @pradiptabasu , you need to install `request` yourself before you install `request-promise`. See the [installation instructions](https://github.com/request/request-promise#installation).

thank you it worked for me..

**Comment by g4brielklein** [comment]
> Hey @pradiptabasu , you need to install `request` yourself before you install `request-promise`. See the [installation instructions](https://github.com/request/request-promise#installation).

Thanks!
