### ISSUE TITLE
error with nw.js

### ISSUE THREAD

**Issue by chovy** [request/request-promise#41]
```
$ nw .
Possibly unhandled Error: TypeError: Illegal invocation
    at Object.ensureErrorObject (/Users/username/projects/rank/node_modules/request-promise/node_modules/bluebird/js/main/util.js:228:20)
    at Promise._rejectCallback (/Users/username/projects/rank/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:416:22)
    at Promise._settlePromiseFromHandler (/Users/username/projects/rank/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:460:17)
    at Promise._settlePromiseAt (/Users/username/projects/rank/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/username/projects/rank/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/username/projects/rank/node_modules/request-promise/node_modules/bluebird/js/main/async.js:164:16)
    at Async._drainQueues (/Users/username/projects/rank/node_modules/request-promise/node_modules/bluebird/js/main/async.js:174:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/username/projects/rank/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:321:17)
```

Here's my code:

```
var rp = require('request-promise');

rp('http://www.google.com')
    .then(console.dir)
    .catch(console.error);
```

**Comment by analog-nico** [comment]
Hi @chovy I never used nw.js before. To reproduce the issue I tried `npm init` then `npm install nw` then `node_modules/.bin/nw .` with your code being in index.js. Apparently there is more to do to get the code running. Can you give me the steps to set it up?

**Comment by analog-nico** [comment]
Hi @chovy I analyzed the error. It turns out Request works fine but when Request-Promise resolves the Bluebird promise the crash happens.

The same error appears with this code - which is roughly what Request-Promise uses internally:
``` js
(new BPromise(function (resolve, reject) {
    request('http://www.google.com', function (err, response, body) {
        if (err) { reject(err); return; }
        resolve(body);
    });
}))
    .then(console.dir)
    .catch(console.error);
```

To narrow it down the same error appears even here:
``` js
(new BPromise(function (resolve) {
    resolve('test');
}))
    .then(console.log);
```

Or even here:
``` js
BPromise.resolve('test')
    .then(console.log);
```

I created an issue for the Bluebird project to discuss this further: https://github.com/petkaantonov/bluebird/issues/623

**Comment by analog-nico** [comment]
@chovy There was a reply in the [Bluebird issue](https://github.com/petkaantonov/bluebird/issues/623). The error is related to the difference between node.js and node-webkit. You have to bind the console methods:

``` js
var rp = require('request-promise');

rp('http://www.google.com')
    .then(console.dir.bind(console))
    .catch(console.error.bind(console));
```

**Comment by anthonyettinger** [comment]
@analog-nico thanks for looking into that!
