### ISSUE TITLE
Possibly unhandled StatusCodeError: 400

### ISSUE THREAD

**Issue by luanmuniz** [request/request-promise#47]
When i receive the StatusCode 400 from a server i have this error

```
Possibly unhandled StatusCodeError: 400 - { errorMessage: "Unable to complete Request", errorCode: 1 }
    at new StatusCodeError (/api/node_modules/request-promise/lib/errors.js:26:15)
    at Request.RP$callback [as _callback] (/api/node_modules/request-promise/lib/rp.js:58:34)
    at Request.self.callback (/api/node_modules/request/request.js:360:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/api/node_modules/request/request.js:1202:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/api/node_modules/request/request.js:1150:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

Should i post this issue at the `request` module?

**Comment by analog-nico** [comment]
Hi @luanmuniz that is definitely something related to the promise functionality. It means that you either did not register an error handler (`.catch( < error handler here> )` or `.then(..., < error handler here >)`) or you register it too late - which would be an advanced use case.

If you show me your code snippet I could help.

**Comment by luanmuniz** [comment]
Yes. You are right! I did not register the error handler for this specific scenario. Sorry about that.
I was expecting to just not execute the success function and ignore the error. 
Its good that we are forced to handle the error, thank you for that! :D

**Comment by analog-nico** [comment]
Indeed, this message comes from Bluebird and is a good design choice. Have a good day!
