### ISSUE TITLE
Error thrown on 3xx HTTP status

### ISSUE THREAD

**Issue by cpetrov** [request/request-promise#62]
```stacktrace
Possibly unhandled StatusCodeError: 302 - 
    at new StatusCodeError (/[...]/node_modules/request-promise/lib/errors.js:26:15)
    at Request.RP$callback [as _callback] (/[...]/node_modules/request-promise/lib/rp.js:64:32)
    at Request.self.callback (/[...]/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/[...]/node_modules/request/request.js:1063:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/[...]/node_modules/request/request.js:1009:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
```

This makes `followRedirect` set to *false* unusable.

**Comment by analog-nico** [comment]
Did you try using the `simple` option set to *false*?

**Comment by cpetrov** [comment]
Thank you for the information. I have missed this from the documentation.

**Comment by analog-nico** [comment]
No problem. BTW, if you want to use this option in many of your calls you may use the `.defaults(...)` function so you don't have to set it every time:
``` js
var rp = require('request-promise').defaults({ simple: false });
```

**Comment by cpetrov** [comment]
This will be useful for my use case. Thank you for the information.

**Comment by szkrd** [comment]
Shouldn't simple:true only reject 4XX and 5XX? To me that would still cover the simple behaviour.

**Comment by analog-nico** [comment]
@szkrd Interesting note which made me think. By default you would not get 3xx responses because Request's [`followRedirect` option](https://github.com/request/request#requestoptions-callback) defaults to `true`. But if you set it to `false` and use the simple mode then 3xx responses are better handled as a rejection I think. Thoughts?

**Comment by szkrd** [comment]
In the end I handled them manually, but simple and non simple error handling differs significantly which just took me by surprise in a couple of my tests.
